baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
enableEmoji = true

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "content/posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 8

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[languages]
  [languages.en]
    languageName = "English"
    title = "Nishant Rodrigues"
    subtitle = ""
    owner = "Nishant Rodrigues"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Nishant Rodrigues"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "About me"
        name = "About me"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "Awards"
        name = "Awards"
        url = "/awards"
      [[languages.en.menu.main]]
        identifier = "Connect"
        name = "Connect"
        url = "/connect"
       [[languages.en.menu.main]]
        identifier = "Experience"
        name = "Experience"
        url = "/experience"
       [[languages.en.menu.main]]
        identifier = "Projects"
        name = "Projects"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "publications"
        name = "Publications"
        url = "/publications"
      [[languages.en.menu.main]]
        identifier = "Talks"
        name = "Talks"
        url = "/talks"
      [[languages.en.menu.main]]
        identifier = "Resume"
        name = "Resume"
        url = "https://nishant-rodrigues.github.io/resume.pdf"
